spring.application.name=property-rental
spring.datasource.url=jdbc:postgresql://localhost:5432/property_rental
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate